auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}
    github:
      development:
        clientId: Ov23liC3SygIxxGY2VMa
        clientSecret: 0b502f3b66562cb3fa5aebda529f6a2168db958c
